### ISSUE TITLE
Track site search keywords

### ISSUE THREAD

**Issue by tsteur** [piwik/developer-documentation#16]
Today I was wondering whether our blog post series already has a positive effect on developer.piwik.org and was analyzing the traffic a bit. During this I noticed we do not track the keywords used in our search.

Goal of this ticket would be to see what people are searching for. This can be useful to know to be able to decide about which topics we should write more and which topics should be covered in a blog post next etc

**Comment by mattab** [comment]
fixed in #68, I can see data on [the demo](http://demo.piwik.org/index.php?module=CoreHome&action=index&date=2015-02-06&period=day&idSite=36#/module=Actions&action=indexSiteSearch&date=2015-02-06&period=day&idSite=36) after few hours:
![search kwds](https://cloud.githubusercontent.com/assets/466765/6077643/e9e10b30-ae55-11e4-8e98-8a15bd8da4ef.png)

This will be very interesting!

**Comment by mnapoli** [comment]
Ha didn't see this one!
