### ISSUE TITLE
Documentation anchors not working

### ISSUE THREAD

**Issue by NicoHood** [piwik/developer-documentation#410]
When clicking at the table of contents the anchor links do not work:
https://developer.matomo.org/api-reference/PHP-Matomo-Tracker#setcustimension
https://developer.matomo.org/api-reference/PHP-Matomo-Tracker#clearcustimensions
https://developer.matomo.org/api-reference/PHP-Matomo-Tracker#getcustimension

I am not sure if other anchors are also affected, I guess the reason is a typo

**Comment by tsteur** [comment]
Thanks for creating the issue @NicoHood where are those links mentioned?

**Comment by Starker3** [comment]
I just ran into this issue when looking for something in the developer docs.

The links are all directly after each other under Methods in the PHP-Matomo-Tracker docs:

setCustomDimension() — Sets a specific custom dimension
clearCustomDimensions() — Clears all previously set custom dimensions
getCustomDimension() — Returns the value of the custom dimension with the given id

Can be fixed by replacing
#setcustimension with #setcustomdimension
#clearcustimensions with #clearcustomdimensions
#getcustimension with #getcustomdimension

**Comment by heurteph-ei** [comment]
Is seems it can be closed now: links about custom dimensions are working well now, in the left menu...

**Comment by justinvelluppillai** [comment]
I will close this now. There are still a few issues for example if there are two submenu items with the same name in the left menu they won't link to the section correctly but there is another issue which should address this issue https://github.com/matomo-org/developer-documentation/issues/673
